In [1]:
import tsl
import torch
import torch_geometric

from torch.optim import Adam
from tsl.datasets import PeMS04, PeMS07, PeMS08, PemsBay
from tsl.datasets import MetrLA

import numpy as np
import pandas as pd

from tqdm import tqdm

In [8]:
root_path = '../data/pems-raw/'
pems03 = np.load(root_path + 'PEMS03/PEMS03.npz')
pems04 = np.load(root_path + 'PEMS04/PEMS04.npz')
pems07 = np.load(root_path + 'PEMS07/PEMS07.npz')
pems08 = np.load(root_path + 'PEMS08/PEMS08.npz')

In [11]:
pems_series = [pems03, pems04, pems07, pems08]
pems_names = ['PEMS03', 'PEMS04', 'PEMS07', 'PEMS08']

for i, pems in enumerate(pems_series):
    print(f"File: {pems_names[i]}")
    for key in pems.files:
        array = pems[key]
        print(f"Array: {key}")
        print(f"  Shape: {array.shape}")
        print(f"  Data type: {array.dtype}")
        print(f"  Size: {array.size}")
        print(f"  Dimensions: {array.ndim}")
        print()


File: PEMS03
Array: data
  Shape: (26208, 358, 1)
  Data type: float64
  Size: 9382464
  Dimensions: 3

File: PEMS04
Array: data
  Shape: (16992, 307, 3)
  Data type: float64
  Size: 15649632
  Dimensions: 3

File: PEMS07
Array: data
  Shape: (28224, 883, 1)
  Data type: float64
  Size: 24921792
  Dimensions: 3

File: PEMS08
Array: data
  Shape: (17856, 170, 3)
  Data type: float64
  Size: 9106560
  Dimensions: 3



In [26]:
pems03_csv = pd.read_csv(root_path + 'PEMS03/PEMS03.csv')
pems04_csv = pd.read_csv(root_path + 'PEMS04/PEMS04.csv')
pems07_csv = pd.read_csv(root_path + 'PEMS07/PEMS07.csv')
pems08_csv = pd.read_csv(root_path + 'PEMS08/PEMS08.csv')

pems_csv_series = [pems03_csv, pems04_csv, pems07_csv, pems08_csv]

In [27]:
for pems_csv in pems_csv_series:
    print(pems_csv.head())
    print()

     from      to  distance
0  317842  318711     0.872
1  318721  315955     1.322
2  315927  318236     1.222
3  318711  318721     0.233
4  318236  317843     1.220

   from   to   cost
0    73    5  352.6
1     5  154  347.2
2   154  263  392.9
3   263   56  440.8
4    56   96  374.6

   from   to   cost
0   721  445  0.790
1   542  480  2.575
2   770  702  0.926
3    32  266  0.596
4    34   56  0.628

   from   to   cost
0     9  153  310.6
1   153   62  330.9
2    62  111  332.9
3   111   11  324.2
4    11   28  336.0



In [50]:
max_node = pems03_csv['from'].max()
min_node = pems03_csv['from'].min()

max_node, min_node

(np.int64(318844), np.int64(311903))

In [47]:
len(pems08_csv['from'].unique())

163

In [58]:
print(pems08['data'][:, :, :].reshape(-1, pems08['data'].shape[1]))

[[1.33e+02 6.03e-02 6.58e+01 ... 6.93e+01 8.60e+01 2.68e-02]
 [6.57e+01 6.70e+01 1.70e-02 ... 1.51e-02 6.86e+01 4.50e+01]
 [2.04e-02 6.79e+01 9.10e+01 ... 6.00e+00 3.10e-03 6.50e+01]
 ...
 [1.02e+02 5.65e-02 6.17e+01 ... 6.74e+01 9.00e+01 3.78e-02]
 [6.25e+01 3.70e+01 9.50e-03 ... 2.74e-02 4.50e+01 4.60e+01]
 [1.96e-02 6.86e+01 8.90e+01 ... 6.00e+00 2.60e-03 6.52e+01]]
